# Generated by Django 4.2.20 on 2025-12-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review_table',
            new_name='Complaint_table',
        ),
    ]
