# Generated by Django 4.2.20 on 2025-12-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_review_table_complaint_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_table',
            name='time',
            field=models.TimeField(),
        ),
    ]
