# Generated by Django 4.2.20 on 2025-12-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_service_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_document_table',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
