# Generated by Django 4.2.20 on 2025-12-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='question',
            field=models.TextField(),
        ),
    ]
