# Generated by Django 4.2.20 on 2025-12-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_chatbot_answer_alter_chatbot_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_table',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
