# Generated by Django 4.2.20 on 2026-03-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_complaint_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_table',
            name='time',
            field=models.IntegerField(),
        ),
    ]
