# Generated by Django 4.2.20 on 2026-03-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_service_table_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('BOOKING_DETAILS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking_details_table')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff_table')),
            ],
        ),
    ]
