# Generated by Django 4.2.20 on 2026-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_staff_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_timing',
            name='end_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff_timing',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
