# Generated by Django 4.2.20 on 2026-03-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_staff_timing_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_timing',
            name='BOOKING_DETAILS',
        ),
        migrations.AddField(
            model_name='staff_timing',
            name='BOOKING',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking_table'),
        ),
    ]
